name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

name: super-lint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  super-lint:
    name: Lint code base
    run: make lint
