name: Super-Linter

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Lint code base
        run: make lint
        working-directory: ./


